import Farm from './farm/farm';
import Nature from './nature/nature';
import StaticItem from '../../entities/Elements/Statics/Static';
import BgItem from '../../entities/Elements/Backgrounds/Background';
import Player from '../../entities/Player/Player';
import WaterItem from '../../entities/Elements/Statics/Water';

const height = 800;
const defaultSize = Nature.defaultSize;
const floor = height - defaultSize * 5;


const backgrounds = [
	Nature.backgrounds.trees.big(250, floor, 20),
	Nature.backgrounds.bush.big.yellow(800, floor, 30),
	Farm.houses.square(defaultSize * 10, height - defaultSize * 5, 200)
];

const loadBackgrounds = factory => {
	backgrounds.forEach((el, idx) => {
		const entity = new BgItem({ ...el, factory, element: "water" });
		factory.addToBodies(entity.body);
		factory.addToEntities(entity);
	});
};

const ground = [

	Nature.statics.ground.ledge.left(defaultSize * 0, height),
	Nature.statics.ground.ledge.middle(defaultSize * 1, height),
	Nature.statics.ground.ledge.middle(defaultSize * 2, height),
	Nature.statics.ground.ledge.middle(defaultSize * 3, height),
	Nature.statics.ground.ledge.middle(defaultSize * 4, height),
	Nature.statics.ground.ledge.right(defaultSize * 5, height),

	Nature.statics.ground.inside.left(defaultSize * 0, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 1, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 2, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 3, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 4, height - defaultSize),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize),

	Nature.statics.ground.inside.left(defaultSize * 0, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 1, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 2, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 3, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 4, height - defaultSize * 2),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize * 2),

	Nature.statics.ground.inside.left(defaultSize * 0, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 1, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 2, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 3, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 4, height - defaultSize * 3),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize * 3),

	Nature.statics.ground.upper.left(defaultSize * 9, height - defaultSize * 4),
	Nature.statics.ground.upper.middle(defaultSize * 10, height - defaultSize * 4),
	Nature.statics.ground.upper.middle(defaultSize * 11, height - defaultSize * 4),
	Nature.statics.ground.upper.middle(defaultSize * 12, height - defaultSize * 4),
	Nature.statics.ground.upper.right(defaultSize * 13, height - defaultSize * 4),


	Nature.statics.ground.inside.left(defaultSize * 9, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 10, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 11, height - defaultSize * 3),
	Nature.statics.ground.inside.middle(defaultSize * 12, height - defaultSize * 3),
	Nature.statics.ground.inside.right(defaultSize * 13, height - defaultSize * 3),

	Nature.statics.ground.inside.left(defaultSize * 9, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 10, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 11, height - defaultSize * 2),
	Nature.statics.ground.inside.middle(defaultSize * 12, height - defaultSize * 2),
	Nature.statics.ground.inside.right(defaultSize * 13, height - defaultSize * 2),

	Nature.statics.ground.inside.left(defaultSize * 9, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 10, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 11, height - defaultSize),
	Nature.statics.ground.inside.middle(defaultSize * 12, height - defaultSize),
	Nature.statics.ground.inside.right(defaultSize * 13, height - defaultSize),

	Nature.statics.ground.ledge.left(defaultSize * 9, height),
	Nature.statics.ground.ledge.middle(defaultSize * 10, height),
	Nature.statics.ground.ledge.middle(defaultSize * 11, height),
	Nature.statics.ground.ledge.middle(defaultSize * 12, height),
	Nature.statics.ground.ledge.right(defaultSize * 13, height),






	Nature.statics.ground.upper.left(0, height - defaultSize * 4),
	Nature.statics.ground.upper.middle(defaultSize, height - defaultSize * 4),
	Nature.statics.ground.upper.middle(defaultSize * 2, height - defaultSize * 4),
	Nature.statics.ground.corner.left.horisontal(defaultSize * 3, height - defaultSize * 4),
	Nature.statics.ground.corner.left.corner(defaultSize * 4, height - defaultSize * 4),
	Nature.statics.ground.corner.left.vertical(defaultSize * 4, height - defaultSize * 5),
	Nature.statics.ground.inside.left(defaultSize * 4, height - defaultSize * 6),
	Nature.statics.ground.upper.left(defaultSize * 4, height - defaultSize * 7),
	Nature.statics.ground.upper.right(defaultSize * 5, height - defaultSize * 7),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize * 6),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize * 5),
	Nature.statics.ground.inside.right(defaultSize * 5, height - defaultSize * 4),









	Nature.statics.ground.cornice.left(defaultSize * 18, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 19, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 20, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 21, height - defaultSize * 6),
	Nature.statics.ground.cornice.right(defaultSize * 22, height - defaultSize * 6),

	Nature.statics.ground.cornice.left(defaultSize * 26, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 27, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 28, height - defaultSize * 6),
	Nature.statics.ground.cornice.right(defaultSize * 29, height - defaultSize * 6),

	Nature.statics.ground.cornice.left(defaultSize * 34, height - defaultSize * 6),
	Nature.statics.ground.cornice.middle(defaultSize * 35, height - defaultSize * 6),
	Nature.statics.ground.cornice.right(defaultSize * 36, height - defaultSize * 6),

	Nature.statics.ground.cornice.left(defaultSize * 42, height - defaultSize * 6),
	Nature.statics.ground.cornice.right(defaultSize * 43, height - defaultSize * 6),

	// Nature.statics.ground.ledge.left(defaultSize * 47, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 48, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 49, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 50, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 51, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 52, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 53, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 54, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 55, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 56, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 57, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 58, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 59, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 60, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 61, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 62, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 63, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 64, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 65, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 66, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 67, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 68, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 69, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 70, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 71, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 72, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 73, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 74, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 75, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 76, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 77, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 78, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 79, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 80, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 81, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 82, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 83, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 84, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 85, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 86, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 87, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 88, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 89, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 90, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 91, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 92, height),
	// Nature.statics.ground.ledge.middle(defaultSize * 93, height),
	// Nature.statics.ground.ledge.right(defaultSize * 94, height),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 79, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 80, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 81, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 82, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 83, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 84, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 85, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 86, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 87, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 88, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 89, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 90, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 91, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 92, height - defaultSize),
	// Nature.statics.ground.inside.middle(defaultSize * 93, height - defaultSize),
	// Nature.statics.ground.inside.right(defaultSize * 94, height - defaultSize),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 79, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 80, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 81, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 82, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 83, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 84, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 85, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 86, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 87, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 88, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 89, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 90, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 91, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 92, height - defaultSize * 2),
	// Nature.statics.ground.inside.middle(defaultSize * 93, height - defaultSize * 2),
	// Nature.statics.ground.inside.right(defaultSize * 94, height - defaultSize * 2),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 79, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 80, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 81, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 82, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 83, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 84, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 85, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 86, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 87, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 88, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 89, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 90, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 91, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 92, height - defaultSize * 3),
	// Nature.statics.ground.inside.middle(defaultSize * 93, height - defaultSize * 3),
	// Nature.statics.ground.inside.right(defaultSize * 94, height - defaultSize * 3),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 79, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 80, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 81, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 82, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 83, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 84, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 85, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 86, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 87, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 88, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 89, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 90, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 91, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 92, height - defaultSize * 4),
	// Nature.statics.ground.inside.middle(defaultSize * 93, height - defaultSize * 4),
	// Nature.statics.ground.inside.right(defaultSize * 94, height - defaultSize * 4),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 5),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 5),
	// Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 5),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 6),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 6),
	// Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 6),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 7),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 7),
	// Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 7),

	// Nature.statics.ground.inside.left(defaultSize * 47, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 48, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 49, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 50, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 51, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 52, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 53, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 54, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 55, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 56, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 57, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 58, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 60, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 61, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 62, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 63, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 8),
	// Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 8),
	// Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 8),

	Nature.statics.ground.upper.left(defaultSize * 47, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 48, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 49, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 50, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 51, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 52, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 53, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 54, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 55, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 56, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 57, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 58, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 59, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 60, height - defaultSize * 9),
	Nature.statics.ground.upper.middle(defaultSize * 61, height - defaultSize * 9),
	Nature.statics.ground.corner.left.horisontal(defaultSize * 62, height - defaultSize * 9),
	Nature.statics.ground.corner.left.corner(defaultSize * 63, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 9),
	Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 9),
	Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 9),

	Nature.statics.ground.cornice.left(defaultSize * 52, height - defaultSize * 12),
	Nature.statics.ground.cornice.middle(defaultSize * 53, height - defaultSize * 12),
	Nature.statics.ground.cornice.right(defaultSize * 54, height - defaultSize * 12),

	Nature.statics.ground.ledge.middle(defaultSize * 59, height - defaultSize * 12),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 13),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 14),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 15),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 16),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 17),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 18),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 19),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 20),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 21),
	Nature.statics.ground.inside.middle(defaultSize * 59, height - defaultSize * 22),

	Nature.statics.ground.cornice.middle(defaultSize * 60, height - defaultSize * 15),
	Nature.statics.ground.cornice.middle(defaultSize * 61, height - defaultSize * 15),
	Nature.statics.ground.cornice.right(defaultSize * 62, height - defaultSize * 15),

	Nature.statics.ground.inside.left(defaultSize * 63, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 10),
	Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 10),
	Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 10),

	Nature.statics.ground.inside.left(defaultSize * 63, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 64, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 65, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 66, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 67, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 68, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 70, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 71, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 72, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 73, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 74, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 75, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 76, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 11),
	Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 11),
	Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 11),

	Nature.statics.ground.upper.left(defaultSize * 63, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 64, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 65, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 66, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 67, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 68, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 69, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 70, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 71, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 72, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 73, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 74, height - defaultSize * 12),
	Nature.statics.ground.upper.middle(defaultSize * 75, height - defaultSize * 12),
	Nature.statics.ground.corner.left.horisontal(defaultSize * 76, height - defaultSize * 12),
	Nature.statics.ground.corner.left.corner(defaultSize * 77, height - defaultSize * 12),
	Nature.statics.ground.inside.middle(defaultSize * 78, height - defaultSize * 12),
	Nature.statics.ground.inside.right(defaultSize * 79, height - defaultSize * 12),

	Nature.statics.ground.ledge.middle(defaultSize * 69, height - defaultSize * 15),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 16),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 17),
	Nature.statics.ground.cornice.middle(defaultSize * 69, height - defaultSize * 18),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 18),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 19),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 20),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 21),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 22),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 23),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 24),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 25),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 26),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 27),
	Nature.statics.ground.inside.middle(defaultSize * 69, height - defaultSize * 28),

	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 13),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 14),
	Nature.statics.ground.cornice.middle(defaultSize * 77, height - defaultSize * 15),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 15),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 16),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 17),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 18),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 19),
	Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 20),
	Nature.statics.ground.cornice.middle(defaultSize * 77, height - defaultSize * 21),
	Nature.statics.ground.inside.middle(defaultSize * 77, height - defaultSize * 21),

	Nature.statics.ground.cornice.left(defaultSize * 75, height - defaultSize * 15),
	Nature.statics.ground.cornice.middle(defaultSize * 76, height - defaultSize * 15),

	Nature.statics.ground.cornice.middle(defaultSize * 70, height - defaultSize * 18),
	Nature.statics.ground.cornice.right(defaultSize * 71, height - defaultSize * 18),

	Nature.statics.ground.upper.left(defaultSize * 75, height - defaultSize * 21),
	Nature.statics.ground.upper.middle(defaultSize * 76, height - defaultSize * 21),

	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 22),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 23),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 24),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 25),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 26),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 27),
	// Nature.statics.ground.inside.left(defaultSize * 77, height - defaultSize * 28),



];

const loadGround = factory => {
	ground.forEach((el, idx) => {
		const entity = new StaticItem({ ...el, factory, element: "ground" });
		factory.addToBodies(entity.body);
		factory.addToEntities(entity);
	})
};

const water = [



	Nature.statics.water.up(defaultSize * 5, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 6, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 7, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 8, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 9, height - defaultSize * 4),

	Nature.statics.water.inside(defaultSize * 5, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 6, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 7, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 8, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 9, height - defaultSize * 3),

	Nature.statics.water.inside(defaultSize * 5, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 6, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 7, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 8, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 9, height - defaultSize * 2),

	Nature.statics.water.inside(defaultSize * 5, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 6, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 7, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 8, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 9, height - defaultSize),

	Nature.statics.water.inside(defaultSize * 5, height),
	Nature.statics.water.inside(defaultSize * 6, height),
	Nature.statics.water.inside(defaultSize * 7, height),
	Nature.statics.water.inside(defaultSize * 8, height),
	Nature.statics.water.inside(defaultSize * 9, height),




	Nature.statics.water.up(defaultSize * 13, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 14, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 15, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 16, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 17, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 18, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 19, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 20, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 21, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 22, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 23, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 24, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 25, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 26, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 27, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 28, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 29, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 30, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 31, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 32, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 33, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 34, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 35, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 36, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 37, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 38, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 39, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 40, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 41, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 42, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 43, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 44, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 45, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 46, height - defaultSize * 4),
	Nature.statics.water.up(defaultSize * 47, height - defaultSize * 4),

	Nature.statics.water.inside(defaultSize * 13, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 14, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 15, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 16, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 17, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 18, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 19, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 20, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 21, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 22, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 23, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 24, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 25, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 26, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 27, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 28, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 29, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 30, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 31, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 32, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 33, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 34, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 35, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 36, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 37, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 38, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 39, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 40, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 41, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 42, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 43, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 44, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 45, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 46, height - defaultSize * 3),
	Nature.statics.water.inside(defaultSize * 47, height - defaultSize * 3),

	Nature.statics.water.inside(defaultSize * 13, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 14, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 15, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 16, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 17, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 18, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 19, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 20, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 21, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 22, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 23, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 24, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 25, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 26, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 27, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 28, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 29, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 30, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 31, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 32, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 33, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 34, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 35, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 36, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 37, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 38, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 39, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 40, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 41, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 42, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 43, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 44, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 45, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 46, height - defaultSize * 2),
	Nature.statics.water.inside(defaultSize * 47, height - defaultSize * 2),

	Nature.statics.water.inside(defaultSize * 13, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 14, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 15, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 16, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 17, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 18, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 19, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 20, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 21, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 22, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 23, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 24, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 25, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 26, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 27, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 28, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 29, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 30, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 31, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 32, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 33, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 34, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 35, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 36, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 37, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 38, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 39, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 40, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 41, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 42, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 43, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 44, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 45, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 46, height - defaultSize),
	Nature.statics.water.inside(defaultSize * 47, height - defaultSize),

	Nature.statics.water.inside(defaultSize * 13, height),
	Nature.statics.water.inside(defaultSize * 14, height),
	Nature.statics.water.inside(defaultSize * 15, height),
	Nature.statics.water.inside(defaultSize * 16, height),
	Nature.statics.water.inside(defaultSize * 17, height),
	Nature.statics.water.inside(defaultSize * 18, height),
	Nature.statics.water.inside(defaultSize * 19, height),
	Nature.statics.water.inside(defaultSize * 20, height),
	Nature.statics.water.inside(defaultSize * 21, height),
	Nature.statics.water.inside(defaultSize * 22, height),
	Nature.statics.water.inside(defaultSize * 23, height),
	Nature.statics.water.inside(defaultSize * 24, height),
	Nature.statics.water.inside(defaultSize * 25, height),
	Nature.statics.water.inside(defaultSize * 26, height),
	Nature.statics.water.inside(defaultSize * 27, height),
	Nature.statics.water.inside(defaultSize * 28, height),
	Nature.statics.water.inside(defaultSize * 29, height),
	Nature.statics.water.inside(defaultSize * 30, height),
	Nature.statics.water.inside(defaultSize * 31, height),
	Nature.statics.water.inside(defaultSize * 32, height),
	Nature.statics.water.inside(defaultSize * 33, height),
	Nature.statics.water.inside(defaultSize * 34, height),
	Nature.statics.water.inside(defaultSize * 35, height),
	Nature.statics.water.inside(defaultSize * 36, height),
	Nature.statics.water.inside(defaultSize * 37, height),
	Nature.statics.water.inside(defaultSize * 38, height),
	Nature.statics.water.inside(defaultSize * 39, height),
	Nature.statics.water.inside(defaultSize * 40, height),
	Nature.statics.water.inside(defaultSize * 41, height),
	Nature.statics.water.inside(defaultSize * 42, height),
	Nature.statics.water.inside(defaultSize * 43, height),
	Nature.statics.water.inside(defaultSize * 44, height),
	Nature.statics.water.inside(defaultSize * 45, height),
	Nature.statics.water.inside(defaultSize * 46, height),
	Nature.statics.water.inside(defaultSize * 47, height),

];

const loadWater = factory => {
	water.forEach((el, idx) => {
		const entity = new WaterItem({ ...el, factory, element: "water" });
		factory.addToBodies(entity.body);
		factory.addToEntities(entity);
	})
};

const loadtTriggers = (factory) => {
	factory.triggers = [
		{
			condition: factory => factory.entities.player.body.position.x >= 200 && factory.triggers[0].done === false,
			action: (factory) => factory.addBird.call(factory, 1500, 200),
			done: false,
		},
		{
			condition: factory => factory.entities.player.body.position.x >= 600 && factory.triggers[1].done === false,
			action: (factory) => factory.addGolem.call(factory, 1000, 300),
			done: false,
		},
	]
};

const loadPlayer = (factory) => {
	const player = new Player({ left: 100, top: -200, factory });
	factory.entities.player = player;
	factory.addToBodies(player.body);
}


const setup = factory => {
	console.log(factory.entities);
	loadGround(factory);
	loadWater(factory);
	loadBackgrounds(factory);
	loadtTriggers(factory);
	loadPlayer(factory);
};

export default {
	setup: (factory) => setup(factory)
};